//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.Lar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lar.IDB")]
    public interface IDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB/GetAllIdosos", ReplyAction="http://tempuri.org/IDB/GetAllIdososResponse")]
        System.Data.DataSet GetAllIdosos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB/GetAllIdosos", ReplyAction="http://tempuri.org/IDB/GetAllIdososResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllIdososAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBChannel : WCFClient.Lar.IDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBClient : System.ServiceModel.ClientBase<WCFClient.Lar.IDB>, WCFClient.Lar.IDB {
        
        public DBClient() {
        }
        
        public DBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllIdosos() {
            return base.Channel.GetAllIdosos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllIdososAsync() {
            return base.Channel.GetAllIdososAsync();
        }
    }
}
